export const dummyDataLineTimeline = {
  lineNumber: 4,
  finalStationStopName: 'Dúbravka',
  timeline: [
    {
      dateTime: '2021-09-02T09:40:13.541Z',
      stopName: 'Lúčanka',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:41:13.541Z',
      stopName: 'Strečnianska',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:42:13.541Z',
      stopName: 'Šintavská',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:43:13.541Z',
      stopName: 'Topoľčianska',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:44:13.541Z',
      stopName: 'TECHNOpol',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:40:13.541Z',
      stopName: 'Lúčanka',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:41:13.541Z',
      stopName: 'Strečnianska',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:42:13.541Z',
      stopName: 'Šintavská',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:43:13.541Z',
      stopName: 'Topoľčianska',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:44:13.541Z',
      stopName: 'TECHNOpol',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:40:13.541Z',
      stopName: 'Lúčanka',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:41:13.541Z',
      stopName: 'Strečnianska',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:42:13.541Z',
      stopName: 'Šintavská',
      active: false,
    },
    {
      dateTime: '2021-09-02T09:43:13.541Z',
      stopName: 'Topoľčianska',
      active: true,
    },
    {
      dateTime: '2021-09-02T09:44:13.541Z',
      stopName: 'TECHNOpol',
      active: false,
    },
  ],
}

export const dummyDataTimetable = {
  lineNumber: 4,
  startStationStopName: 'Trnavské mýto',
  finalStationStopName: 'Dúbravka',
  timetable: [
    {
      hour: 4,
      minutes: [
        { minute: 22, additionalInfo: 's' },
        { minute: 30, additionalInfo: null },
        { minute: 46, additionalInfo: null },
        { minute: 52, additionalInfo: null },
      ],
    },
    {
      hour: 5,
      minutes: [
        { minute: 0, additionalInfo: null },
        { minute: 8, additionalInfo: null },
        { minute: 16, additionalInfo: null },
        { minute: 23, additionalInfo: null },
        { minute: 31, additionalInfo: null },
        { minute: 38, additionalInfo: null },
        { minute: 42, additionalInfo: null },
        { minute: 46, additionalInfo: null },
        { minute: 53, additionalInfo: null },
      ],
    },
    {
      hour: 6,
      minutes: [
        { minute: 1, additionalInfo: null },
        { minute: 8, additionalInfo: null },
        { minute: 16, additionalInfo: null },
        { minute: 23, additionalInfo: null },
        { minute: 28, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 44, additionalInfo: null },
        { minute: 49, additionalInfo: null },
        { minute: 54, additionalInfo: null },
        { minute: 59, additionalInfo: null },
      ],
    },
    {
      hour: 7,
      minutes: [
        { minute: 4, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 14, additionalInfo: null },
        { minute: 19, additionalInfo: null },
        { minute: 24, additionalInfo: null },
        { minute: 29, additionalInfo: null },
        { minute: 34, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 44, additionalInfo: null },
        { minute: 49, additionalInfo: null },
        { minute: 54, additionalInfo: null },
        { minute: 59, additionalInfo: null },
      ],
    },
    {
      hour: 8,
      minutes: [
        { minute: 4, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 14, additionalInfo: null },
        { minute: 19, additionalInfo: null },
        { minute: 25, additionalInfo: null },
        { minute: 31, additionalInfo: null },
        { minute: 37, additionalInfo: null },
        { minute: 40, additionalInfo: 's' },
        { minute: 43, additionalInfo: null },
        { minute: 49, additionalInfo: null },
        { minute: 55, additionalInfo: null },
      ],
    },
    {
      hour: 9,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 10,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 11,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 12,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 13,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 14,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 15,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 16,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 17,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 18,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 19,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 20,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 21,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 22,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
    {
      hour: 23,
      minutes: [
        { minute: 3, additionalInfo: null },
        { minute: 9, additionalInfo: null },
        { minute: 12, additionalInfo: null },
        { minute: 15, additionalInfo: null },
        { minute: 21, additionalInfo: null },
        { minute: 27, additionalInfo: null },
        { minute: 33, additionalInfo: null },
        { minute: 39, additionalInfo: null },
        { minute: 45, additionalInfo: null },
        { minute: 51, additionalInfo: null },
        { minute: 57, additionalInfo: null },
      ],
    },
  ],
}

export const dummyDataPlaceHistory = [
  {
    text: 'Laurinská',
    location: { lat: 48.143790966468266, lon: 17.110766155720967 },
  },
  {
    text: 'Krížna',
    location: { lat: 48.15525939712473, lon: 17.12428358270609 },
  },
  {
    text: 'Laurinská',
    location: { lat: 48.143790966468266, lon: 17.110766155720967 },
  },
  {
    text: 'Krížna',
    location: { lat: 48.15525939712473, lon: 17.12428358270609 },
  },
  {
    text: 'Laurinská',
    location: { lat: 48.143790966468266, lon: 17.110766155720967 },
  },
  {
    text: 'Krížna',
    location: { lat: 48.15525939712473, lon: 17.12428358270609 },
  },
  {
    text: 'Laurinská',
    location: { lat: 48.143790966468266, lon: 17.110766155720967 },
  },
  {
    text: 'Krížna',
    location: { lat: 48.15525939712473, lon: 17.12428358270609 },
  },
  {
    text: 'Laurinská',
    location: { lat: 48.143790966468266, lon: 17.110766155720967 },
  },
  {
    text: 'Krížna',
    location: { lat: 48.15525939712473, lon: 17.12428358270609 },
  },
  {
    text: 'Laurinská',
    location: { lat: 48.143790966468266, lon: 17.110766155720967 },
  },
  {
    text: 'Krížna',
    location: { lat: 48.15525939712473, lon: 17.12428358270609 },
  },
  {
    text: 'Laurinská',
    location: { lat: 48.143790966468266, lon: 17.110766155720967 },
  },
  {
    text: 'Krížna',
    location: { lat: 48.15525939712473, lon: 17.12428358270609 },
  },
  {
    text: 'Laurinská',
    location: { lat: 48.143790966468266, lon: 17.110766155720967 },
  },
  {
    text: 'Krížna',
    location: { lat: 48.15525939712473, lon: 17.12428358270609 },
  },
  {
    text: 'Laurinská',
    location: { lat: 48.143790966468266, lon: 17.110766155720967 },
  },
  {
    text: 'Krížna final, Krížna final Krížna final Krížna final',
    location: { lat: 48.15525939712473, lon: 17.12428358270609 },
  },
]
