services:
  api: 
    build:
      context: app
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    # Map the app volume to the host volume
    volumes:
      - ./app:/app
